env:
  global:
  - DISTRO=ubuntu-18.04
  - TESTS=true
  - PACKAGE=ocaml-protoc-plugin
  - PINS="conf-protoc:."
language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
sudo: required
services:
- docker
dist: bionic
script: bash -ex .travis-docker.sh

jobs:
  include:
    - os: linux
      env: OCAML_VERSION=4.06
    - os: linux
      env: OCAML_VERSION=4.11
    - os: osx
      install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
      script: bash -ex .travis-opam.sh
      env: OCAML_VERSION=4.11
    - os: linux
      env: OCAML_VERSION=4.06
      language: node_js
      node_js:
        - 12
      script: npm install && npm run build
